test:
  _target_: src.datasets.BaseDataset
  instance_transforms: ${transforms.instance_transforms.inference}
  segment: 'inference'
  index:
    - text: 'Printing, in the only sense with which we are at present concerned, differs from most if not from all the arts and crafts represented in the Exhibition.'
      path: "text.txt"
      audio_len: 0
