train:
  _target_: src.datasets.LJspeechDatasetKaggle
  part: "train"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.LJspeechDatasetKaggle
  part: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
