test:
  _target_: src.datasets.CustomDirTextDataset
  instance_transforms: ${transforms.instance_transforms.inference}
  data_dir: /Users/vera/Desktop/hifi/HiFi-GAN/data/datasets/ljspeech/test/transcriptions
