defaults:
  - generator: hifigan
  - metrics: default
  - datasets: audio # we do not want to run inference on training data
  - dataloader: hifigan
  - transforms: mel_spec
  - _self_
inferencer:
  device_tensors: ["spectrogram", "audio"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "result" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "./saved/model_best-5.pth" # path to the pretrained model
text: null