defaults:
  - generator: hifigan
  - discriminator: hifigan
  - writer: wandb
  - metrics: example
  - datasets: ljspeech_kaggle
  - dataloader: example
  - transforms: mel_spec
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.99999
loss_function:
  _target_: src.loss.GenLoss
d_loss_function:
  _target_: src.loss.DiscLoss
trainer:
  log_step: 500
  n_epochs: 80
  epoch_len: 500
  device_tensors: ["spectrogram", "audio"] # which tensors should be on device (ex. GPU)
  from_pretrained: /kaggle/input/hifigan-best2/model_best.pth
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min test_loss" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
