_target_: src.logger.WandBWriter
project_name: "dla-hw3-hifigan"
entity: null
run_name: "testing"
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
audio_sample_rate: 22050
